#include "hand.h"


/** Includes */

#include "svg.h"
#include "path.h"
#include "parse.h"

#include "text.h"
#include "shapes.h"

#include "mod_ext.h"

#include "recursiveCursor.h"

//#include "complexEle.h"


/** Variables */

extern struct svg *global_svg;

// TODO, this should be autogenerated and auto iterated?
int numFonts = 1;


extern int xmlFuncts_arr_len_jalbSvg;
extern struct xmlFuncts *xmlFuncts_arr_jalbSvg[];

/*
extern int len_backbone_arr_jalbSvg;
extern struct backbone_structStruct *backbone_arr_jalbSvg[];

extern int svg_attributes[];
extern struct backbone_structStruct svg;
*/

char global_svg_dir[1024] = "\0";

extern int renderMode;

char *pathUnit_string[] = {
	"moveTo",
	"lineTo",
	"cubicBez",
	"quadBez",
	"ellipArc",
	"pathEnd",
};



/** Functions */

void load_global_svg ( char *dir ) {
	printf ( "load_global_svg ( )\n" );
	printf ( "dir: %s\n", dir );

	strcpy ( global_svg_dir, dir );

	struct svg *svgEle = loadXmlFile_03 ( dir, xmlFuncts_arr_jalbSvg, xmlFuncts_arr_len_jalbSvg );
	global_svg = svgEle;

	say_svg ( svgEle );

	printf ( "load_global_svg ( ) OVER\n" );
}

void save_global ( ) {
	printf ( "save_global ( )\n" );
	if ( global_svg_dir[0] == '\0' ) {
		printf ( "globa_svg_dir empty, cant save.\n" );
	}

	save_global_svg ( global_svg_dir );

	printf ( "save_global ( ) OVER\n" );
}

/*
int svgNameToIndex ( char *body, void *data, void *ret, char **strPtr ) {

	struct svg *var = data;
	if ( strcmp ( body, "width" ) == 0 ) {
		return 0;
	} else if ( strcmp ( body, "height" ) == 0 ) {
		return 1;
	} else if ( strcmp ( body, "eles" ) == 0 ) {
		void **ptrPtr = (void**)ret;
		*ptrPtr = var->eles;
		return jxnAlPtr;

	} else if ( strcmp ( body, "g" ) == 0 ) {
		struct nakedUnion *naked = nakedUnionInit ( );
		arrayListAddEndPointer ( var->eles, naked );
		nakedUnionTypeChange0 ( naked, G );

//		nakedUnionTypeChange0 ( var, 0 );
		*strPtr = "g";
		void **retPtr = ret;
//		*retPtr = &var->g;
		*retPtr = &naked->g;
		return jxnPtr;
	}
	return -1;
}
*/


/** Post Init */

void pathPostInit ( void *data ) {
	printf ( "pathPostInit ( )\n" );
	struct path *path = data;

	printf ( "pre\n" );
	sayPath ( path );

	// ok so i need to parse d.
	// i can do this in the BodyToVal, i dont need to do it here.
	// whatever.

	parseD ( path->d, path->eles );

//	printf ( "post parseD\n" );

	generic_postInit ( path, path->style, (void (*)(void *, char *, char *))path_style_handle );

	path->stroke_w = atof ( path->stroke_width );
	printf ( "path->stroke_w: %f\n", path->stroke_w );

	sayPath ( path );

	printf ( "pathPostInit ( ) OVER\n" );
}


#define expand_preprocessor(funct) \
	funct("fill", path->fill) \
	funct("stroke", path->stroke) \
	funct("stroke-width", path->stroke_width) \
	funct("stroke-linecap", path->stroke_linecap) \
	funct("stroke-linejoin", path->stroke_linejoin) \
	funct("stroke-opacity", path->stroke_opacity)


#define path_styleParse(strName,varName) \
	if ( strcmp ( name, strName ) == 0 ) { \
		strcpy ( varName, value ); \
	} else


int debugPrint_styleParse = 1;

void path_style_handle ( struct path *path, char *name, char *value ) {
	if ( debugPrint_styleParse ) {
		printf ( "path_style_handle ( )\n" );
		printf ( "name: %s\n", name );
		printf ( "value: %s\n", value );
	}

/*
	if ( strcmp ( name, "fill" ) == 0 ) {
		strcpy ( path->fill, value );
	} else if ( strcmp ( name, "stroke" ) == 0 ) {
		strcpy ( path->stroke, value );
	} else 
*/
	expand_preprocessor(path_styleParse)
	{
		printf ( "path_style_handle unhandled\n" );
		printf ( "name: %s\n", name );
		printf ( "value: %s\n", value );
	}

	if ( debugPrint_styleParse ) {
		printf ( "path_style_handle ( ) OVER\n" );
	}
}








/** Say */

void say_svg ( struct svg *svg ) {
	printf ( "say_svg ( )\n" );
	printf ( "svg: %p\n", svg );

	if ( !svg ) {
		return;
	}

	printf ( "svg->eles.len: %d\n", arrayListGetLength ( svg->eles ) );

	sayEleList ( svg->eles );

	printf ( "say_svg ( ) OVER\n" );
}


int nakedUni_str_len = 6;
char *nakedUni_str[] = {
	"g",
	"path",
	"text",
	"rect",
	"circ",
	"ellipse",
};

void sayEleList ( ArrayList *eles ) {
//	printf ( "sayEleList ( )\n" );

	int i;
	int len;

	i = 0;
	len = arrayListGetLength ( eles );

	printf ( "eles.len: %d\n", len );

	while ( i < len ) {
		struct nakedUnion *uni = arrayListGetPointer ( eles, i );

//		printf ( "uni->type: %d\n", uni->type );

		if ( uni->type >= 0 ) {
			if ( uni->type < nakedUni_str_len ) {
				printf ( "%s\n", nakedUni_str[uni->type] );
			} else {
				printf ( "uni->type >= nakedUni_str_len: %d >= %d\n", uni->type, nakedUni_str_len );
			}
		} else {
			printf ( "uni->type: %d\n", uni->type );
		}

		if ( uni->type == G ) {
			struct g *g = uni->g;
			printf ( "id: %s\n", g->id );
			printf ( "numEles: %d\n", arrayListGetLength ( g->eles ) );

			sayEleList ( g->eles );

		} else if ( uni->type == Path ) {
			struct path *path = uni->path;
			printf ( "style: %s\n", path->style );
			printf ( "d: %s\n", path->d );
			printf ( "id: %s\n", path->id );

			printf ( "path->eles.len: %d\n", arrayListGetLength ( path->eles ) );

			sayPath ( path );

		} else if ( uni->type == Text ) {
			struct text *text = uni->text;
			say_svgText ( text );

		}

		i += 1;
	}
}

void say_svgText ( struct text *text ) {
	int i;
	int len;

	i = 0;
	len = arrayListGetLength ( text->spanList );

	printf ( "spanList.len: %d\n", len );

	while ( i < len ) {

		struct tspan *span = arrayListGetPointer ( text->spanList, i );

//		printf ( "span: %p\n", span );
		printf ( "span: %s\n", span->body );
		printf ( "{ %f, %f }\n", span->x, span->y );

		i += 1;
	}
}

void sayPath ( struct path *path ) {
	printf ( "sayPath ( )\n" );

	printf ( "style: %s\n", path->style );
	printf ( "d: %s\n", path->d );
	printf ( "id: %s\n", path->id );

	int i;
	int len;

	i = 0;
	len = arrayListGetLength ( path->eles );
	printf ( "len: %d\n", len );
	while ( i < len ) {
		struct pathUni *uni = arrayListGetPointer ( path->eles, i );
		sayPathUni ( uni );

		i += 1;
	}

	printf ( "path->fill: %s\n", path->fill );
	printf ( "path->stroke: %s\n", path->stroke );

	printf ( "sayPath ( ) OVER\n" );
}

void say_pathUni_type ( int i ) {
	if ( i >= 0 &&
	     i <= path_PathEnd ) {
		printf ( "uni->type: %s\n", pathUnit_string[i] );
	} else {
		printf ( "pathUni->type out of bounds. [%d]\n", i );
	}
}

void sayPathUni ( struct pathUni *uni ) {
//	printf ( "sayPathUni ( )\n" );

//	printf ( "uni->type: %d\n", uni->type );
	say_pathUni_type ( uni->type );
	if ( uni->type == path_MoveTo ) {
		sayFloatArray ( "moveTo->XY", uni->moveTo->XY, 2 );
	} else if ( uni->type == path_LineTo ) {
		sayFloatArray ( "lineTo->XY", uni->lineTo->XY, 2 );
	} else if ( uni->type == path_CubicBez ) {
		sayFloatArray ( "cubicBez->XY", uni->cubicBez->XY, 2 );
	} else if ( uni->type == path_QuadBez ) {
		sayFloatArray ( "quadBez->XY", uni->quadBez->XY, 2 );
	} else if ( uni->type == path_EllipArc ) {
		sayFloatArray ( "ellipArc->XY", uni->ellipArc->XY, 2 );
	}

//	printf ( "sayPathUni ( ) OVER\n" );
}

int isBlankSpace( char c ) {
	if ( c == ' ' ||
	     c == '\t' ||
	     c == '\n' ||
	     c == '\r' ) {
		return 1;
	}
	return 0;
}


/** to paste

// svgNameToIndex
// gNameToIndex
// pathNameToIndex // path have subs like this?

	// this should be able to be handled by a function, where i return the union struct? or null, im not sure.
	} else if ( strcmp ( body, "g" ) == 0 ) {
		struct nakedUnion *naked = nakedUnionInit ( );
		arrayListAddEndPointer ( var->eles, naked );
		nakedUnionTypeChange0 ( naked, G );

//		nakedUnionTypeChange0 ( var, 0 );
		*strPtr = "g";
		void **retPtr = ret;
//		*retPtr = &var->g;
		*retPtr = &naked->g;
		return jxnPtr;

	} else if ( strcmp ( body, "path" ) == 0 ) {
		struct nakedUnion *naked = nakedUnionInit ( );
		arrayListAddEndPointer ( var->eles, naked );
		nakedUnionTypeChange0 ( naked, Path );

//		nakedUnionTypeChange0 ( var, 0 );
		*strPtr = "path";
		void **retPtr = ret;
		*retPtr = &naked->path;
		return jxnPtr;

	} else if ( strcmp ( body, "text" ) == 0 ) {
		struct nakedUnion *naked = nakedUnionInit ( );
		arrayListAddEndPointer ( var->eles, naked );
		nakedUnionTypeChange0 ( naked, Text );

//		nakedUnionTypeChange0 ( var, 0 );
		*strPtr = "text";
		void **retPtr = ret;
		*retPtr = &naked->text;
		return jxnPtr;

	} else if ( strcmp ( body, "rect" ) == 0 ) {
		struct nakedUnion *naked = nakedUnionInit ( );
		arrayListAddEndPointer ( var->eles, naked );
		nakedUnionTypeChange0 ( naked, Rect );

//		nakedUnionTypeChange0 ( var, 0 );
		*strPtr = "rect";
		void **retPtr = ret;
		*retPtr = &naked->rect;
		return jxnPtr;

	} else if ( strcmp ( body, "circle" ) == 0 ) {
		struct nakedUnion *naked = nakedUnionInit ( );
		arrayListAddEndPointer ( var->eles, naked );
		nakedUnionTypeChange0 ( naked, Circle );

//		nakedUnionTypeChange0 ( var, 0 );
		*strPtr = "circle";
		void **retPtr = ret;
		*retPtr = &naked->circle;
		return jxnPtr;

	} else if ( strcmp ( body, "ellipse" ) == 0 ) {
		struct nakedUnion *naked = nakedUnionInit ( );
		arrayListAddEndPointer ( var->eles, naked );
		nakedUnionTypeChange0 ( naked, Ellipse );

//		nakedUnionTypeChange0 ( var, 0 );
		*strPtr = "ellipse";
		void **retPtr = ret;
		*retPtr = &naked->ellipse;
		return jxnPtr;



struct xmlFuncts pathXml = {
	"path",
	pathInitMask,
	pathNameToIndex,
	pathBodyToVal,

	.postInit = pathPostInit,
};

*/



void expandSvg ( struct svg *svg ) {
	expandEleList ( svg->eles );
}

void expandEleList ( ArrayList *eles ) {
	int i;
	int len;

	i = 0;
	len = arrayListGetLength ( eles );

	while ( i < len ) {
		struct nakedUnion *uni = arrayListGetPointer ( eles, i );

		if ( uni->type == G ) {
			struct g *g = uni->g;

			expandEleList ( g->eles );

		} else if ( uni->type == Path ) {
			struct path *path = uni->path;

//			eleListToD ( path->eles, path->d );
			parseD ( path->d, path->eles );
		}

		i += 1;
	}
}

/** Other */

void hand_load ( char *dir ) {
	printf ( "hand_load ( )\n" );
	printf ( "dir: %s\n", dir );

	struct svg *svgEle = loadXmlFile_03 ( dir, xmlFuncts_arr_jalbSvg, xmlFuncts_arr_len_jalbSvg );
	say_svg ( svgEle );


	printf ( "hand_load ( ) OVER\n" );
}







void hand_p ( char *dir ) {
	printf ( "hand_p ( )\n" );

	jalbScreenshot_ppm ( dir );

	printf ( "hand_p ( ) OVER\n" );
}

/** postInit */

void textPostInit ( struct text *text ) {
	printf ( "textPostInit ( )\n" );
	printf ( "text->style: %s\n", text->style );

	generic_postInit ( text, text->style, (void (*)(void *, char *, char *))text_style_handle );

/*
	int i;
	int len;

	char *style = text->style;

	int type = 0;
	int s = 0;
	char name[256];
	char value[256];

	i = 0;
	len = strlen ( style );
	while ( i < len ) {
		char c = style[i];

		if ( c == ':' ) {
			name[s] = '\0';
			type = 1;
			s = 0;
		} else if ( c == ';' ) {
			// handle.
			value[s] = '\0';
			type = 0;
			s = 0;

			text_style_handle ( text, name, value );

		} else if ( type == 0 ) {
			name[s] = c;
			s += 1;
		} else if ( type == 1 ) {
			value[s] = c;
			s += 1;
		}

		i += 1;
	}
*/

//	strToFloatIndex

	printf ( "textPostInit ( ) OVER\n" );
}

void tspanPostInit ( struct tspan *tspan ) {
	printf ( "tspanPostInit ( )\n" );
	printf ( "tspan->style: %s\n", tspan->style );
	printf ( "tspan->body: %s\n", tspan->body );

	generic_postInit ( tspan, tspan->style, (void (*)(void *, char *, char *))tspan_style_handle );

	int i;
	int len;

/*
	char *style = tspan->style;

	int type = 0;
	int s = 0;
	char name[256];
	char value[256];

	i = 0;
	len = strlen ( style );
	while ( i < len ) {
		char c = style[i];

		if ( c == ':' ) {
			name[s] = '\0';
			type = 1;
			s = 0;
		} else if ( c == ';' ) {
			// handle.
			value[s] = '\0';
			type = 0;
			s = 0;

			tspan_style_handle ( tspan, name, value );

		} else if ( type == 0 ) {
			name[s] = c;
			s += 1;
		} else if ( type == 1 ) {
			value[s] = c;
			s += 1;
		}

		i += 1;
	}
*/

	i = 0;
	len = strlen ( tspan->body );
	while ( i < len ) {
		char *c = arrayListGetNext ( tspan->stringBuilder );
		*c = tspan->body[i];
		i += 1;
	}

	printf ( "tspanPostInit ( ) OVER\n" );
}

void tspan_style_handle ( struct tspan *tspan, char *name, char *value ) {
	printf ( "tspan_style_handle ( )\n" );
	printf ( "name: %s\n", name );
	printf ( "value: %s\n", value );

	if ( strcmp ( name, "font-size" ) == 0 ) {
		tspan->fontSize = atof ( value );
		printf ( "tspan->fontSize: %f\n", tspan->fontSize );
	}
}

void text_style_handle ( struct text *text, char *name, char *value ) {
	printf ( "text_style_handle ( )\n" );
	printf ( "name: %s\n", name );
	printf ( "value: %s\n", value );

	if ( strcmp ( name, "font-size" ) == 0 ) {
		// TODO font size is in span only now.
//		text->fontSize = atof ( value );
//		printf ( "text->fontSize: %f\n", text->fontSize );
	}
}


/** Errand Manager */

void empty_global_svg ( ) {
	printf ( "empty_global_svg ( )\n" );

	if ( global_svg ) {
		printf ( "global_svg not null, return\n" );
		return;
	}
	global_svg = svgInit ( );

	struct nakedUnion *naked = nakedUnionInit ( );
	arrayListAddEndPointer ( global_svg->eles, naked );
	nakedUnionTypeChange0 ( naked, G );

	printf ( "empty_global_svg ( ) OVER\n" );
}

void hand_errand_00 ( ) {
	printf ( "hand_errand_00 ( )\n" );

	if ( !global_svg ) {
		printf ( "!global_svg, return\n" );
		return;
	}

	char *name = "eleName";
	char *desc = "element description";

	struct svg *svg = global_svg;

	struct nakedUnion *naked = arrayListGetPointer ( svg->eles, 0 );
	printf ( "naked: %p\n", naked );

	struct g *g = naked->g;
	printf ( "g: %p\n", g );

	float XY[2] = { 100, 100 };
	int indent = 10;
	float WH[2] = { 200, 100 };
	add_errand ( g, XY, name, desc );

	int addChild = 1;
	if ( addChild ) {
		// if ele->hasChild

		// Path to fist child.
		struct nakedUnion *naked = nakedUnionInit ( );
		arrayListAddEndPointer ( g->eles, naked );
		nakedUnionTypeChange0 ( naked, Path );
		struct path *path = naked->path;

		struct pathUni *puni = pathUniInit ( );
		arrayListAddEndPointer ( path->eles, puni );
		pathUniTypeChange0 ( puni, path_MoveTo );
		puni->moveTo->XY[0] = XY[0] + indent;
		puni->moveTo->XY[1] = XY[1] + WH[1];

		puni = pathUniInit ( );
		arrayListAddEndPointer ( path->eles, puni );
		pathUniTypeChange0 ( puni, path_LineTo );

		float joint[2];
		joint[0] = XY[0] + indent;
		joint[1] = XY[1] + WH[1] + indent * 2 + indent;

//		puni->lineTo->XY[0] = XY[0] + indent;
//		puni->lineTo->XY[1] = XY[1] + WH[1] + indent * 2 + indent;
		puni->lineTo->XY[0] = joint[0];
		puni->lineTo->XY[1] = joint[1];

		puni = pathUniInit ( );
		arrayListAddEndPointer ( path->eles, puni );
		pathUniTypeChange0 ( puni, path_LineTo );
		puni->lineTo->XY[0] = XY[0] + indent + indent;
		puni->lineTo->XY[1] = XY[1] + WH[1] + indent * 2 + indent;

		char *name = "Child Name";
		char *desc = "the description of the child";

		XY[0] += indent * 2;
		XY[1] += WH[1] + 20;

		add_errand ( g, XY, name, desc );

		XY[0] -= indent * 2;


		// Path to second child.
		naked = nakedUnionInit ( );
		arrayListAddEndPointer ( g->eles, naked );
		nakedUnionTypeChange0 ( naked, Path );
		path = naked->path;

		puni = pathUniInit ( );
		arrayListAddEndPointer ( path->eles, puni );
		pathUniTypeChange0 ( puni, path_MoveTo );
		puni->moveTo->XY[0] = joint[0];
		puni->moveTo->XY[1] = joint[1];

		puni = pathUniInit ( );
		arrayListAddEndPointer ( path->eles, puni );
		pathUniTypeChange0 ( puni, path_LineTo );
		puni->lineTo->XY[0] = XY[0] + indent;
		puni->lineTo->XY[1] = XY[1] + WH[1] + indent * 2 + indent;

		puni = pathUniInit ( );
		arrayListAddEndPointer ( path->eles, puni );
		pathUniTypeChange0 ( puni, path_LineTo );
		puni->lineTo->XY[0] = XY[0] + indent + indent;
		puni->lineTo->XY[1] = XY[1] + WH[1] + indent * 2 + indent;

		{
			char name[256];
			strcpy ( name, "Second Childs Name" );
			char desc[256];
			strcpy ( desc, "the description of the OTHER child" );

			XY[0] += indent * 2;
			XY[1] += WH[1] + 20;

			add_errand ( g, XY, name, desc );
		}
	}
}

void add_errand ( struct g *g, float *XY, char *name, char *desc ) {
	int indent = 10;
	int WH[2] = { 200, 100 };

	struct nakedUnion *uniRect = nakedUnionInit ( );
	arrayListAddEndPointer ( g->eles, uniRect );

	nakedUnionTypeChange0 ( uniRect, Rect );
	struct rect *rect = uniRect->rect;
	rect->x = XY[0];
	rect->y = XY[1];
	rect->width = WH[0];
	rect->height = WH[1];

	struct nakedUnion *uni = nakedUnionInit ( );
	arrayListAddEndPointer ( g->eles, uni );

	nakedUnionTypeChange0 ( uni, Text );
	struct text *text = uni->text;
//	text->fontSize = 8;

	float fontSize = 8.0;
	float gap = 2.0;

	struct tspan *span = tspanInit ( );
	arrayListAddEndPointer ( text->spanList, span );
	span->fontSize = fontSize;
	span->x = XY[0] + indent;
	span->y = XY[1] + indent;
	strcpy ( span->body, name );
	tspanPostInit ( span );
	printSb ( span->stringBuilder );


	span = tspanInit ( );
	arrayListAddEndPointer ( text->spanList, span );
	span->fontSize = fontSize;
	span->x = XY[0] + indent;
	span->y = XY[1] + indent + fontSize + gap;
	strcpy ( span->body, desc );
	tspanPostInit ( span );
	printSb ( span->stringBuilder );
}


//extern int num_structStruct_jalbSvg;
extern struct xmlFuncts *xmlFuncts_arr_jalbSvg[];

extern int len_backbone_arr_jalbSvg;
extern struct backbone_structStruct *backbone_arr_jalbSvg[];

extern int svg_attributes[];
extern struct backbone_structStruct backboneStru_svg;

void save_global_xml ( char *dir ) {
	printf ( "save_global_xml ( )\n" );
	printf ( "dir: %s\n", dir );

	struct svg *svgEle = global_svg;

	// fwriteXml_backbone
	fwriteXml_backbone ( dir, &backboneStru_svg, svgEle,
		svg_attributes, backbone_arr_jalbSvg, len_backbone_arr_jalbSvg );

	printf ( "save_global_xml ( ) OVER\n" );
}

void save_global_svg ( char *dir ) {
	printf ( "save_global_svg ( )\n" );
	printf ( "dir: %s\n", dir );

	struct svg *svgEle = global_svg;
	svg_preSave ( svgEle );

	fwriteXml_backbone ( dir, &backboneStru_svg, svgEle,
		svg_attributes, backbone_arr_jalbSvg, len_backbone_arr_jalbSvg );

	printf ( "save_global_svg ( ) OVER\n" );
}


/** Pre Save */

#define path_styleFill(strName,varName) \
	if ( varName[0] != '\0' ) { \
		if ( i != 0 ) { \
			buffer[i] = ';'; \
			i += 1; \
			buffer[i] = '\0'; \
		} \
		i += sprintf ( &buffer[i], strName":%s", varName ); \
	}

void svg_preSave ( struct svg *svg ) {
	printf ( "svg_preSave ( )\n" );

	preSave_nakedList ( svg->eles );

	printf ( "svg_preSave ( ) OVER\n" );
}

void preSave_nakedList ( ArrayList *eles ) {
	printf ( "preSave_nakedList ( )\n" );

	int i;
	int len;

	i = 0;
	len = arrayListGetLength ( eles );

	while ( i < len ) {
		struct nakedUnion *uni = arrayListGetPointer ( eles, i );

		preSave_nakedUnion ( uni );

		i += 1;
	}
}

void preSave_nakedUnion ( struct nakedUnion *uni ) {
	if ( uni->type == G ) {
		preSave_g ( uni->g );
	} else if ( uni->type == Path ) {
		preSave_path ( uni->path );
	} else if ( uni->type == Text ) {
		preSave_text ( uni->text );
	} else if ( uni->type == Rect ) {
		preSave_rect ( uni->rect );
	}
}

void preSave_g ( struct g *g ) {
	preSave_nakedList ( g->eles );
}

void preSave_path ( struct path *path ) {
	printf ( "preSave_path ( )\n" );

	printf ( "path->d: %s\n", path->d );

	eleListToD ( path->eles, path->d );
	printf ( "path->d: %s\n", path->d );

	path->style[0] = '\0';
	compile_path_style ( path );
}

void preSave_text ( struct text *text ) {
	printf ( "preSave_text ( )\n" );

	// TODO, do this in span now.
//	char *buffer = text->style;
//	int bi = 0;
//	sprintf ( &buffer[bi], "font-size:%fpx", text->fontSize );

	int i;
	int len;
	i = 0;
	len = arrayListGetLength ( text->spanList );
	while ( i < len ) {
		struct tspan *tspan = arrayListGetPointer ( text->spanList, i );

		preSave_tspan ( tspan );

		i += 1;
	}

	printf ( "preSave_text ( ) OVER\n" );
}

void preSave_tspan ( struct tspan *tspan ) {
	printf ( "tspan->body: %s\n", tspan->body );

/*
	char *buffer = tspan->style;
	int i = 0;

	strcpy ( &buffer[i], "font-size:%fpx", tspan->fontSize );
*/
}

void preSave_rect ( struct rect *rect ) {
	char *buffer = rect->style;
	int i = 0;

	path_styleFill("fill", rect->fill)
	path_styleFill("stroke", rect->stroke)
	path_styleFill("stroke-width", rect->stroke_width)
	path_styleFill("stroke-opacity", rect->stroke_opacity)
}

void compile_path_style ( struct path *path ) {
	char *buffer = path->style;
	int i = 0;

	// i can neaten this up, via macros probably.

	// i associate these things here, and also in pathPostInit.
	// so i want them to have this list, but not really indata, just as preprocessor info.
	// but idk if i can have an array of preprocessor data
	// use a macro.
/*
	path_styleFill("fill", path->fill)
	path_styleFill("stroke", path->stroke)
	path_styleFill("stroke-width", path->stroke_width)
	path_styleFill("stroke-linecap", path->stroke_linecap)
	path_styleFill("stroke-linejoin", path->stroke_linejoin)
	path_styleFill("stroke-opacity", path->stroke_opacity)
*/

	expand_preprocessor(path_styleFill);


/*
	if ( path->fill[0] != '\0' ) {
		if ( i != 0 ) {
			buffer[i] = ';';
			i += 1;
			buffer[i] = '\0';
		}
		i += sprintf ( &buffer[i], "fill:%s", path->fill );
	}
	if ( path->stroke[0] != '\0' ) {
		if ( i != 0 ) {
			buffer[i] = ';';
			i += 1;
			buffer[i] = '\0';
		}
		i += sprintf ( &buffer[i], "stroke:%s", path->stroke );
	}
*/
}


/** should be auto generated for the naked structs */
/*
gNameToIndex
svgNameToIndex


	} else {
		int r = nakedStru_nameToIndex ( body, var->eles, ret, strPtr );
		if ( r != -1 ) {
			return r;
		}
	}


	.postInit = pathPostInit,
*/


int nakedStru_nameToIndex ( char *body, ArrayList *eles, void *ret, char **strPtr ) {
	// this should be able to be handled by a function, where i return the union struct? or null, im not sure.
	if ( strcmp ( body, "g" ) == 0 ) {
		struct nakedUnion *naked = nakedUnionInit ( );
		arrayListAddEndPointer ( eles, naked );
		nakedUnionTypeChange0 ( naked, G );

		*strPtr = "g";
		void **retPtr = ret;
		*retPtr = &naked->g;
		return jxnPtr;

	} else if ( strcmp ( body, "path" ) == 0 ) {
		struct nakedUnion *naked = nakedUnionInit ( );
		arrayListAddEndPointer ( eles, naked );
		nakedUnionTypeChange0 ( naked, Path );

		*strPtr = "path";
		void **retPtr = ret;
		*retPtr = &naked->path;
		return jxnPtr;

	} else if ( strcmp ( body, "text" ) == 0 ) {
		struct nakedUnion *naked = nakedUnionInit ( );
		arrayListAddEndPointer ( eles, naked );
		nakedUnionTypeChange0 ( naked, Text );

		*strPtr = "text";
		void **retPtr = ret;
		*retPtr = &naked->text;
		return jxnPtr;

	} else if ( strcmp ( body, "rect" ) == 0 ) {
		struct nakedUnion *naked = nakedUnionInit ( );
		arrayListAddEndPointer ( eles, naked );
		nakedUnionTypeChange0 ( naked, Rect );

		*strPtr = "rect";
		void **retPtr = ret;
		*retPtr = &naked->rect;
		return jxnPtr;

	} else if ( strcmp ( body, "circle" ) == 0 ) {
		struct nakedUnion *naked = nakedUnionInit ( );
		arrayListAddEndPointer ( eles, naked );
		nakedUnionTypeChange0 ( naked, Circle );

		*strPtr = "circle";
		void **retPtr = ret;
		*retPtr = &naked->circle;
		return jxnPtr;

	} else if ( strcmp ( body, "ellipse" ) == 0 ) {
		struct nakedUnion *naked = nakedUnionInit ( );
		arrayListAddEndPointer ( eles, naked );
		nakedUnionTypeChange0 ( naked, Ellipse );

		*strPtr = "ellipse";
		void **retPtr = ret;
		*retPtr = &naked->ellipse;
		return jxnPtr;
	}
	return -1;
}



/** Toggle */

void toggle_renderMode ( ) {
	printf ( "toggle_renderMode ( )\n" );

	renderMode += 1;
	renderMode %= renderM_num;

	printf ( "renderMode: %d\n", renderMode );

	printf ( "toggle_renderMode ( )\n" );
}

void set_renderMode ( int i ) {
	printf ( "set_renderMode ( )\n" );

	renderMode = i;

	printf ( "renderMode: %d\n", renderMode );

	printf ( "set_renderMode ( ) OVER\n" );
}

/// Layout Keywords

void jSvg_preInit ( ArrayList *keyList, ArrayList *modList ) {
	printf ( "jSvg_preInit ( )\n" );

	struct jalbLayKeyword *key = NULL;

	// "svgCtrl:"
	key = malloc ( sizeof ( struct jalbLayKeyword ) );
	strcpy ( key->key, "svgCtrl:" );
	key->funct = jKeyCtrl;
	key->data = NULL;
	arrayListAddEndPointer ( keyList, key );
}

//int debugPrint_ctrl = 0;
ArrayList *glob_ctrlKeys = NULL;

// This is from jalbText.
void jKeyCtrl ( char *line, void *data ) {
//	if ( debugPrint_ctrl ) {
		printf ( "jKeyCtrl: (%s)\n", line );
//	}

//	struct layText *textData = lastTextEle;
	if ( !glob_ctrlKeys ) {
		glob_ctrlKeys = initArrayList ( 10, sizeof ( char ), 10 );
	}

	ArrayList *ctrlKeys = glob_ctrlKeys;

//	if ( line[0] != '\"' ) {
//		return;
//	}

	// this is a really weird way of handing a var, i never do it like this.
	// this var's type of this enum?
	enum { REG,
	       SLASH } state = REG;

	// I should ambiguate this loop?

	char c;

//	int i = 1;
	int i = 0;
	while ( 1 ) {
//		printf("(%d): %c\n", i, line[i]);

		switch ( state ) {
		case REG:
			switch ( line[i] ) {
			case '\0':
				return;
				break;
			case '\n':
				return;
				break;
			case '\"': // End of string.
				return;
				break;
			case '\'':
				// should be preceded, doesnt really matter.
				break;
			case '\\':
				state = SLASH;
				break;
			default:
//				printf ( "&line[i]: %c\n", line[i] );
				arrayListAddEnd ( ctrlKeys, &line[i] );
				break;
			}
			break;
		case SLASH:
			switch ( line[i] ) {
			case 'n':
				c = '\n';
//				printf("c: \\n\n");
				arrayListAddEnd ( ctrlKeys, &c );
				break;
			case 't':
				c = '\t';
//				printf("c: \\t\n");
				arrayListAddEnd ( ctrlKeys, &c );
				break;
			case '\"':
				c = line[i];
//				printf("c: \"\n");
				arrayListAddEnd ( ctrlKeys, &c );
				break;
			case '\'':
				c = line[i];
//				printf("c: \'\n");
				arrayListAddEnd ( ctrlKeys, &c );
				break;
			case '\\':
				c = line[i];
//				printf("c: \\\n");
				arrayListAddEnd ( ctrlKeys, &c );
				break;
			default:
				// unhandled.
				break;
			}
			state = REG;

			break;
		default:
			printf ( "bug\n" );
			return;
			break;
		}
		i += 1;
	}
	printf ( "jKeyCtrl ( ) OVER\n" );;
}





